### ISSUE TITLE
sorry not sure if it is appropriate to post questions here. 

### ISSUE THREAD

**Issue by danqingdong** [ricco386/Udacity-CS101#1]
just two really basics

- i am curious what ".gitignore" is doing in this directory?

- is the file contains the entire "official" answer codes from cs101 for building a search engine? cheers

**Comment by ricco386** [comment]
Hello, 

.gitignore is file where you can specify which files will be ignored by git, for example *.pyc file doesnt make sence to have in version system, similarily hidden OS files, or files from your IDE etc.

this is not official material for the course, this repo is my code that I have done while working on the course...
